// <auto-generated />
using System;
using Fixer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fixer.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fixer.Tmdb.Models.Movie", b =>
                {
                    b.Property<long>("Id");

                    b.Property<bool>("Adult");

                    b.Property<string>("BackdropPath");

                    b.Property<int>("Filters");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("OriginalLanguage");

                    b.Property<string>("OriginalTitle");

                    b.Property<string>("Overview");

                    b.Property<double>("Popularity");

                    b.Property<string>("PosterPath");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.Property<double>("VoteAverage");

                    b.Property<long>("VoteCount");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
